nav:
  ##############################
  - Home: index.md

  ##############################
  - Getting Started:
    - Overview: getting-started/index.md
    - Tutorials:
      - Quickstart:
          - 'Overview': getting-started/quickstart/index.md
          - 'Installation': getting-started/placeholder.md
          - 'Configuring': getting-started/placeholder.md
          - 'Stage and Test': getting-started/placeholder.md
          - 'Deploy': getting-started/placeholder.md
          - 'Metrics': getting-started/placeholder.md
      - 'Specifics':
        - 'Getting Started with Docker': getting-started/tutorials/with-docker.md
        - 'Getting Started with Kubernetes': getting-started/tutorials/with-k8s.md
        - 'Getting Started from scratch': getting-started/tutorials/from-scratch.md
    - Fundamentals:
      - 'Architecture and concepts': getting-started/tutorials/with-docker.md
      - 'On installation methods': getting-started/tutorials/with-docker.md
      - 'Main use cases': getting-started/tutorials/with-docker.md
      - 'Best practices': getting-started/tutorials/with-docker.md
    - Intermediate:
      - 'Certguard and RBAC on perspective': getting-started/learn/placeholder.md
      - 'Content Curation on the RPM ecosystem': getting-started/learn/placeholder.md
      - 'Stable and predictable system': getting-started/learn/placeholder.md
      - 'World-scale scalability': getting-started/learn/placeholder.md
  ##############################
  - User Guides:
    - Overview: guides/index.md
    - 'Content Types':
      - 'File':
          - 'Doing some thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
      - 'RPM Packages':
          - 'Doing some thing': guides/how-placeholder.md
          - 'Doing something else': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
      - 'Debian Packages':
          - 'Doing some thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
      - 'Python Packages':
          - 'Doing some thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
      - 'Npm Packages':
          - 'Doing some thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
      - 'Gem Packages':
          - 'Doing some thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
      - 'Ansible Playbooks':
          - 'Doing some thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
      - 'Container Images':
          - 'Doing some thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
      - 'Maven':
          - 'Doing some thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
      - 'Ostree':
          - 'Doing some thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
      - 'Certguard':
          - 'Doing some thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
          - 'Doing another thing': guides/how-placeholder.md
    - 'General':
          - 'Doing some thing': guides/how-placeholder.md
          - 'Doing some thing': guides/how-placeholder.md
          - 'Doing some thing': guides/how-placeholder.md

  ##############################
  - Reference:
    - Overview: reference/index.md
    - Repositories Map: reference/placeholder.md
    - Glossary: reference/placeholder.md
    - Conent Types:
      - Pulpcore:
        - REST Api: reference/placeholder.md
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - RPM Packages:
        - REST Api: reference/placeholder.md
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'File':
        - REST Api: reference/placeholder.md
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'RPM Packages':
        - REST Api: reference/placeholder.md
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Debian Packages':
        - REST Api: reference/placeholder.md
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Python Packages':
        - REST Api: reference/placeholder.md
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Npm Packages':
        - REST Api: reference/placeholder.md
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Gem Packages':
        - REST Api: reference/placeholder.md
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Ansible Playbooks':
        - REST Api: reference/placeholder.md
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Container Images':
        - REST Api: reference/placeholder.md
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Maven':
        - REST Api: reference/placeholder.md
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Ostree':
        - REST Api: reference/placeholder.md
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Certguard':
        - REST Api: reference/placeholder.md
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
    - 'Tooling':
      - 'CLI':
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Client Library (glue)':
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'OpenAPI Generator':
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Developer Environement':
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
    - 'Resources':
      - 'OCI Images':
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Kubernetes Resources':
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Ansible Modules (squeezer)':
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md
      - 'Selinux':
        - Codebase Api: reference/placeholder.md
        - Changelog: reference/placeholder.md

  ##############################
  - Community:
    - Overview: community/index.md
    - About: community/placeholder.md
    - PulpCon: community/placeholder.md
    - Contributing:
      - Quickstart: community/placeholder.md
      - Guides:
        - Setup the developer environment: community/placeholder.md
        - Contribute to docs: community/placeholder.md
        - Create a new plugin: community/placeholder.md
        - Troubleshoot oci-env: community/placeholder.md
      - Onboarding:
        - Architecture for contributors: community/placeholder.md
        - Database modeling in pulpcore: community/placeholder.md
        - On client, servers and bindings: community/placeholder.md
        - Release cycles and backporting: community/placeholder.md
        - Known limitations: community/placeholder.md
          

site_name: Pulp Project
site_url: https://github.com/pulp/pulpcore
repo_url: https://github.com/pulp/pulpcore
repo_name: pulp/pulpcore
theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: black
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    

plugins:
  - social
  - search
  - tags:
      tags_file: tags.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pulp
    - icon: fontawesome/brands/discourse
      link: https://discourse.pulpproject.org/

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

      # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # - pymdownx.highlight:
  #     anchor_linenums: true
  # - pymdownx.inlinehilite
  # - pymdownx.snippets
  # - pymdownx.arithmatex:
  #     generic: true
  # - pymdownx.details
  # - pymdownx.superfences
  # - pymdownx.mark
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/pulp"  target="_blank" rel="noopener">Pulp Project</a>
